// Export tous les composants UI pour faciliter les imports
export { Toast, ToastProvider, ToastViewport, ToastTitle, ToastDescription, ToastClose, ToastAction, type ToastProps, type ToastActionElement } from './toast'
export { useToast, toast } from '@/lib/hooks/use-toast'
export { default as Breadcrumbs } from './Breadcrumbs'
export { default as LoadingSpinner, LoadingOverlay, LoadingPage, SavingIndicator } from './LoadingSpinner'
export { ConfirmDialogProvider, useConfirm } from './ConfirmDialog'
export { default as EmptyState, NoDataState, SearchEmptyState, ErrorState } from './EmptyState'
export { default as Tooltip, HelpTooltip } from './Tooltip'
export { default as Pagination, SimplePagination } from './Pagination'
export { GlobalKeyboardShortcuts, useKeyboardShortcuts } from './KeyboardShortcuts'
export { default as LanguageSwitcher } from './LanguageSwitcher'
